title: QGames - Hub
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to QGames Hub! This is a place where you can find all the quantum games created by students at the Hague University of Applied Sciences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  treinDotDev

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  games:
    output: true
    permalink: /games/:name

exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
